### ISSUE TITLE
数据库表中信息的获取

### ISSUE THREAD

**Issue by Crowds21** [zhangjl-sjtu/MeteorDiary#1]
想请教一下在TOC模板中,关于循环的部分
```
.action{range $v:=$block}
- ((.action{$v.ID}))
.action{end}
```
这部分是只能访问blocks表中的`ID`属性吗?比如我想获取`box`属性,可以实现吗?我自己试了一下都是error.

**Comment by zhangzz66** [comment]
可以实现的，看一下思源的帮助文档，自定义属性应该在另外一个表里面，好像叫attributes

**Comment by Crowds21** [comment]
解决了, 又去仔细看了一下你的TOC代码, 原来列名要大写 0_0.
```
.action{range $v:=$block}
- .action{$v.Box}
.action{end}
```
感谢
